// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqflmcoisszhixecgzow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZmxtY29pc3N6aGl4ZWNnem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDUxMjAsImV4cCI6MjA3NDQ4MTEyMH0.PJ7W3TRtJByUf5AGqt4H1clRcVMKI66IeGfYMFguWZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});